config/routes.rb
RailsProjects::Application.routes.draw do
  get "ips/scanner_locations"

  get "ips/ScannerLocations"

  resources :beacons

  resources :scanners

  resources :applications
  resources :IPS
  match '/dashboard' => 'applications#dashboard'

  get "heat_maps/show"
  match 'heat_map/map_live', :to => redirect('heat_map/map_live.html')
  match 'heat_map/map_demo', :to => redirect('heat_map/map_demo.html')
  match '/lifelogger', :to => redirect('/public/lifelogger_applications/Lifelogger - CMU.html')
  match 'slider', :to => redirect('/jquery-silider/index.html')

  match 'ips', :to=> redirect('IPS/GoogleMapsOverlay.html')
  post 'scanners/update_scanner_beacon'
  post 'beacons/update_beacons_by_identifier'
  

   root :to => 'welcome#index'

end

app/models/scanner.rb
class Scanner < ActiveRecord::Base
  attr_accessible :beconId, :identifier
  attr_accessor :lat, :lng
end

app/controllers/scanners_controller.rb
class ScannersController < ApplicationController
  # GET /scanners
  # GET /scanners.json
  def index
    @scanners = Scanner.all

    @scanners_with_lat_lan = []
    @scanners.each do |scanner|
      @beacon = Beacon.find_by_identifier(scanner.beconId)
      unless(@beacon.nil?)
        @scanners_with_lat_lan << {
                           beacon_id: scanner.beconId,
                           scanner_identifier: scanner.identifier,
                           latitude: @beacon.lat,
                           longitude: @beacon.lng,
                           location: @beacon.location
          }
      end
    end

    puts json: @scanner_with_lat_lan
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scanners_with_lat_lan }
    end
  end

  # GET /scanners/1
  # GET /scanners/1.json
  def show
    @scanner = Scanner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scanner }
    end
  end

  # GET /scanners/new
  # GET /scanners/new.json
  def new
    @scanner = Scanner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scanner }
    end
  end

  # GET /scanners/1/edit
  def edit
    @scanner = Scanner.find(params[:id])
  end

  # POST /scanners
  # POST /scanners.json
  def create
    @scanner = Scanner.new(params[:scanner])

    respond_to do |format|
      if @scanner.save
        format.html { redirect_to @scanner, notice: 'Scanner was successfully created.' }
        format.json { render json: @scanner, status: :created, location: @scanner }
      else
        format.html { render action: "new" }
        format.json { render json: @scanner.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_scanner_beacon

    # {
    #     "identifier": "SumeetsPhone",
    #     "beconId": "1071619057806538345"
    # }

    identifier = params[:identifier]
    becon_id = params[:beconId]

    if identifier.nil? || becon_id.nil?
      format.json { render :nothing => true, :status => 503 }
    else
      @scanner = Scanner.find_by_identifier(params[:identifier])
      if @scanner 
        @scanner[:beconId] = params[:beconId]
      else
        @scanner = Scanner.new(:identifier => params[:identifier])
      end

      respond_to do |format|
        if @scanner.update_attributes(params[:scanner])
          format.html { redirect_to @scanner, notice: 'Scanner was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @scanner.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /scanners/1
  # PUT /scanners/1.json
  def update
    @scanner = Scanner.find(params[:id])

    respond_to do |format|
      if @scanner.update_attributes(params[:scanner])
        format.html { redirect_to @scanner, notice: 'Scanner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scanner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scanners/1
  # DELETE /scanners/1.json
  def destroy
    @scanner = Scanner.find(params[:id])
    @scanner.destroy

    respond_to do |format|
      format.html { redirect_to scanners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scanners_helper.rb
module ScannersHelper
end

app/views/scanners/_form.html.erb
<%= form_for(@scanner) do |f| %>
  <% if @scanner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scanner.errors.count, "error") %> prohibited this scanner from being saved:</h2>

      <ul>
      <% @scanner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :identifier %>
  </div>
  <div class="field">
    <%= f.label :beconId %><br />
    <%= f.text_field :beconId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scanners/edit.html.erb
<h1>Editing scanner</h1>

<%= render 'form' %>

<%= link_to 'Show', @scanner %> |
<%= link_to 'Back', scanners_path %>

app/views/scanners/index.html.erb
<h1>Listing scanners</h1>

<table>
  <tr>
    <th>Identifier</th>
    <th>Beconid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scanners.each do |scanner| %>
  <tr>
    <td><%= scanner.identifier %></td>
    <td><%= scanner.beconId %></td>
    <td><%= link_to 'Show', scanner %></td>
    <td><%= link_to 'Edit', edit_scanner_path(scanner) %></td>
    <td><%= link_to 'Destroy', scanner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scanner', new_scanner_path %>

app/views/scanners/new.html.erb
<h1>New scanner</h1>

<%= render 'form' %>

<%= link_to 'Back', scanners_path %>

app/views/scanners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Identifier:</b>
  <%= @scanner.identifier %>
</p>

<p>
  <b>Beconid:</b>
  <%= @scanner.beconId %>
</p>


<%= link_to 'Edit', edit_scanner_path(@scanner) %> |
<%= link_to 'Back', scanners_path %>