config/routes.rb
RailsProjects::Application.routes.draw do
  get "ips/scanner_locations"

  get "ips/ScannerLocations"

  resources :beacons

  resources :scanners

  resources :applications
  resources :IPS
  match '/dashboard' => 'applications#dashboard'

  get "heat_maps/show"
  match 'heat_map/map_live', :to => redirect('heat_map/map_live.html')
  match 'heat_map/map_demo', :to => redirect('heat_map/map_demo.html')
  match '/lifelogger', :to => redirect('/public/lifelogger_applications/Lifelogger - CMU.html')
  match 'slider', :to => redirect('/jquery-silider/index.html')

  match 'ips', :to=> redirect('IPS/GoogleMapsOverlay.html')
  post 'scanners/update_scanner_beacon'
  post 'beacons/update_beacons_by_identifier'
  

   root :to => 'welcome#index'

end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
  attr_accessible :identifier, :lat, :lng, :location
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  # GET /beacons
  # GET /beacons.json
  def index
    @beacons = Beacon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beacons }
    end
  end

  # GET /beacons/1
  # GET /beacons/1.json
  def show
    @beacon = Beacon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beacon }
    end
  end

  # GET /beacons/new
  # GET /beacons/new.json
  def new
    @beacon = Beacon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beacon }
    end
  end

  # GET /beacons/1/edit
  def edit
    @beacon = Beacon.find(params[:id])
  end

  # POST /beacons
  # POST /beacons.json
  def create
    @beacon = Beacon.new(params[:beacon])

    respond_to do |format|
      if @beacon.save
        format.html { redirect_to @beacon, notice: 'Beacon was successfully created.' }
        format.json { render json: @beacon, status: :created, location: @beacon }
      else
        format.html { render action: "new" }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beacons/1
  # PUT /beacons/1.json
  def update
    @beacon = Beacon.find(params[:id])

    respond_to do |format|
      if @beacon.update_attributes(params[:beacon])
        format.html { redirect_to @beacon, notice: 'Beacon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_beacons_by_identifier
    # identifier = params[:identifier]
    # becon_id = params[:beconId]
    # "identifier":"7203422764646594139","lat":"37.410459","lng":"-122.059998","location":"B23 Room 117"
    @beacon = Beacon.find_by_identifier(params[:identifier])

    if not @beacon 
        @beacon = Beacon.new(:identifier => params[:identifier])
    end


    respond_to do |format|
      if @beacon.update_attributes(params[:beacon])
        format.html { redirect_to @beacon, notice: 'Beacon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beacons/1
  # DELETE /beacons/1.json
  def destroy
    @beacon = Beacon.find(params[:id])
    @beacon.destroy

    respond_to do |format|
      format.html { redirect_to beacons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/views/beacons/_form.html.erb
<%= form_for(@beacon) do |f| %>
  <% if @beacon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beacon.errors.count, "error") %> prohibited this beacon from being saved:</h2>

      <ul>
      <% @beacon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :identifier %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beacons/edit.html.erb
<h1>Editing beacon</h1>

<%= render 'form' %>

<%= link_to 'Show', @beacon %> |
<%= link_to 'Back', beacons_path %>

app/views/beacons/index.html.erb
<h1>Listing beacons</h1>

<table>
  <tr>
    <th>Identifier</th>
    <th>Location</th>
    <th>Lat</th>
    <th>Lng</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beacons.each do |beacon| %>
  <tr>
    <td><%= beacon.identifier %></td>
    <td><%= beacon.location %></td>
    <td><%= beacon.lat %></td>
    <td><%= beacon.lng %></td>
    <td><%= link_to 'Show', beacon %></td>
    <td><%= link_to 'Edit', edit_beacon_path(beacon) %></td>
    <td><%= link_to 'Destroy', beacon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beacon', new_beacon_path %>

app/views/beacons/new.html.erb
<h1>New beacon</h1>

<%= render 'form' %>

<%= link_to 'Back', beacons_path %>

app/views/beacons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Identifier:</b>
  <%= @beacon.identifier %>
</p>

<p>
  <b>Location:</b>
  <%= @beacon.location %>
</p>

<p>
  <b>Lat:</b>
  <%= @beacon.lat %>
</p>

<p>
  <b>Lng:</b>
  <%= @beacon.lng %>
</p>


<%= link_to 'Edit', edit_beacon_path(@beacon) %> |
<%= link_to 'Back', beacons_path %>