config/routes.rb
RailsProjects::Application.routes.draw do
  get "ips/scanner_locations"

  get "ips/ScannerLocations"

  resources :beacons

  resources :scanners

  resources :applications
  resources :IPS
  match '/dashboard' => 'applications#dashboard'

  get "heat_maps/show"
  match 'heat_map/map_live', :to => redirect('heat_map/map_live.html')
  match 'heat_map/map_demo', :to => redirect('heat_map/map_demo.html')
  match '/lifelogger', :to => redirect('/public/lifelogger_applications/Lifelogger - CMU.html')
  match 'slider', :to => redirect('/jquery-silider/index.html')

  match 'ips', :to=> redirect('IPS/GoogleMapsOverlay.html')
  post 'scanners/update_scanner_beacon'
  post 'beacons/update_beacons_by_identifier'
  

   root :to => 'welcome#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :description, :mobile_url, :name, :web_url, :logo_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_x_frame_options
  #protect_from_forgery

  def set_x_frame_options
    response.headers["X-Frame-Options"] = "ALLOWALL"
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :set_x_frame_options

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def dashboard
    set_x_frame_options
    @applications = Application.all
    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json { render json: @application }
    #end
    render :show_dashboard
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(params[:application])

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  def set_x_frame_options
    response.headers["X-Frame-Options"] = "ALLOWALL"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :logo %><br />
      <%= f.text_field :logo_url %>
    </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :web_url %><br />
    <%= f.text_field :web_url %>
  </div>
  <div class="field">
    <%= f.label :mobile_url %><br />
    <%= f.text_field :mobile_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Logo of Application</th>
    <th>Web url</th>
    <th>Mobile url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applications.each do |application| %>
  <tr>
    <td><%= application.name %></td>
    <td><%= application.description %></td>
    <td><%= application.logo_url %></td>
    <td><%= application.web_url %></td>
    <td><%= application.mobile_url %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @application.name %>
</p>
<p>
  <b>Logo:</b>
  <%= @application.logo_url %>
</p>
<p>
  <b>Description:</b>
  <%= @application.description %>
</p>

<p>
  <b>Web url:</b>

  <iframe src="<%= @application.web_url%>" width="70%" height="400px"><p>Placeholder text; only shows up if the page DOESN'T render!</p></iframe>
</p>

<p>
  <b>Mobile url:</b>
    <iframe src="<%= @application.mobile_url %>" width="400" height="500"><p>Placeholder text; only shows up if the page DOESN'T render!</p></iframe>
</p>


<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/applications/show_dashboard.html.erb
<% @applications.each do |application| %>
    <div>
      <ul>
        <li>
          <img src="<%= application.logo_url %>" >
          <h3><%= application.name %></h3>
          <p><%= application.description %></p>
          <h4><%= application.web_url %></h4>
          <!--<h4><%= application.mobile_url %></h4>-->
        </li>
      </ul>
    </div>
<% end %>

<div>
  <ul>
    <li>
      <img src="http://lorempixum.com/100/100/nature/1" >
      <h3>The Grasslands</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod ultrices ante, ac laoreet nulla vestibulum adipiscing. Nam quis justo in augue auctor imperdiet.</p>
    </li>

    <li>
      <img src="http://lorempixum.com/100/100/nature/2" >
      <h3>Paradise Found</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod ultrices ante, ac laoreet nulla vestibulum adipiscing. Nam quis justo in augue auctor imperdiet.</p>
    </li>

    <li>
      <img src="http://lorempixum.com/100/100/nature/3" >
      <h3>Smoke On The Water</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod ultrices ante, ac laoreet nulla vestibulum adipiscing. Nam quis justo in augue auctor imperdiet.</p>
    </li>

    <li>
      <img src="http://lorempixum.com/100/100/nature/4" >
      <h3>Headline</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod ultrices ante, ac laoreet nulla vestibulum adipiscing. Nam quis justo in augue auctor imperdiet.</p>
    </li>
  </ul>
</div>